// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { starter as jaJP_starter } from "./ja-JP";
import { starter as koKR_starter } from "./ko-KR";
import { starter as zhTW_starter } from "./zh-TW";
import { starter as frFR_starter } from "./fr-FR";
import { starter as deDE_starter } from "./de-DE";
import { starter as esES_starter } from "./es-ES";
import { starter as ptBR_starter } from "./pt-BR";
import { starter as ruRU_starter } from "./ru-RU";
import { starter as itIT_starter } from "./it-IT";
import { starter as nlNL_starter } from "./nl-NL";
import { starter as trTR_starter } from "./tr-TR";
import { starter as plPL_starter } from "./pl-PL";
import { starter as viVN_starter } from "./vi-VN";
import { starter as thTH_starter } from "./th-TH";
import { starter as idID_starter } from "./id-ID";
import { starter as arEG_starter } from "./ar-EG";
import { starter as csCZ_starter } from "./cs-CZ";
import { starter as heIL_starter } from "./he-IL";
import { starter as hiIN_starter } from "./hi-IN";
import { starter as svSE_starter } from "./sv-SE";
import { starter as ukUA_starter } from "./uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "starter": {
    "ja-JP": jaJP_starter,
    "ko-KR": koKR_starter,
    "zh-TW": zhTW_starter,
    "fr-FR": frFR_starter,
    "de-DE": deDE_starter,
    "es-ES": esES_starter,
    "pt-BR": ptBR_starter,
    "ru-RU": ruRU_starter,
    "it-IT": itIT_starter,
    "nl-NL": nlNL_starter,
    "tr-TR": trTR_starter,
    "pl-PL": plPL_starter,
    "vi-VN": viVN_starter,
    "th-TH": thTH_starter,
    "id-ID": idID_starter,
    "ar-EG": arEG_starter,
    "cs-CZ": csCZ_starter,
    "he-IL": heIL_starter,
    "hi-IN": hiIN_starter,
    "sv-SE": svSE_starter,
    "uk-UA": ukUA_starter,
  },
};
